"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .accessdetails import AccessDetails, AccessDetailsTypedDict, Level
from .accesstoken import (
    AccessToken,
    AccessTokenTypedDict,
    AccessTokenUser,
    AccessTokenUserTypedDict,
    Claims,
    ClaimsTypedDict,
    WorkspacesModel,
    WorkspacesModelTypedDict,
)
from .accounttype import AccountType
from .activatesubscriptionnamespaceop import (
    ActivateSubscriptionNamespaceRequest,
    ActivateSubscriptionNamespaceRequestTypedDict,
)
from .addtags import AddTags, AddTagsTypedDict
from .annotations import Annotations, AnnotationsTypedDict
from .apierror import APIError
from .apikeydetails import APIKeyDetails, APIKeyDetailsTypedDict
from .checkgithubaccessop import (
    CheckGithubAccessRequest,
    CheckGithubAccessRequestTypedDict,
)
from .clievent import CliEvent, CliEventTypedDict, GenerateBumpType, OpenapiDiffBumpType
from .codesampleschemainput import (
    CodeSampleSchemaInput,
    CodeSampleSchemaInputTypedDict,
    SchemaFile,
    SchemaFileTypedDict,
)
from .codesamplesjobstatus import CodeSamplesJobStatus
from .createop import CreateRequestBody, CreateRequestBodyTypedDict
from .createworkspacetokenop import (
    CreateWorkspaceTokenGlobals,
    CreateWorkspaceTokenGlobalsTypedDict,
    CreateWorkspaceTokenRequest,
    CreateWorkspaceTokenRequestTypedDict,
)
from .deleteworkspacetokenop import (
    DeleteWorkspaceTokenGlobals,
    DeleteWorkspaceTokenGlobalsTypedDict,
    DeleteWorkspaceTokenRequest,
    DeleteWorkspaceTokenRequestTypedDict,
)
from .diagnostic import Diagnostic, DiagnosticTypedDict
from .error import Error, ErrorData
from .featureflag import FeatureFlag, FeatureFlagTypedDict
from .generatecodesamplepreviewasyncop import (
    GenerateCodeSamplePreviewAsyncResponseBody,
    GenerateCodeSamplePreviewAsyncResponseBodyTypedDict,
)
from .generatecodesamplepreviewop import (
    GenerateCodeSamplePreviewResponse,
    GenerateCodeSamplePreviewResponseTypedDict,
)
from .getaccesstokenop import GetAccessTokenRequest, GetAccessTokenRequestTypedDict
from .getblobop import GetBlobRequest, GetBlobRequestTypedDict
from .getchangesreportsignedurlop import (
    GetChangesReportSignedURLRequest,
    GetChangesReportSignedURLRequestTypedDict,
    GetChangesReportSignedURLSignedAccess,
    GetChangesReportSignedURLSignedAccessTypedDict,
)
from .getcodesamplepreviewasyncop import (
    GetCodeSamplePreviewAsyncRequest,
    GetCodeSamplePreviewAsyncRequestTypedDict,
    GetCodeSamplePreviewAsyncResponse,
    GetCodeSamplePreviewAsyncResponseBody,
    GetCodeSamplePreviewAsyncResponseBodyTypedDict,
    GetCodeSamplePreviewAsyncResponseTypedDict,
)
from .getgithubactionop import GetGitHubActionRequest, GetGitHubActionRequestTypedDict
from .getgithubsetupstateop import (
    GetGithubSetupStateRequest,
    GetGithubSetupStateRequestTypedDict,
)
from .getlintingreportsignedurlop import (
    GetLintingReportSignedURLRequest,
    GetLintingReportSignedURLRequestTypedDict,
    GetLintingReportSignedURLSignedAccess,
    GetLintingReportSignedURLSignedAccessTypedDict,
)
from .getmanifestop import GetManifestRequest, GetManifestRequestTypedDict
from .getnamespacesresponse import GetNamespacesResponse, GetNamespacesResponseTypedDict
from .getorganizationop import GetOrganizationRequest, GetOrganizationRequestTypedDict
from .getrevisionsop import GetRevisionsRequest, GetRevisionsRequestTypedDict
from .getrevisionsresponse import GetRevisionsResponse, GetRevisionsResponseTypedDict
from .gettagsop import GetTagsRequest, GetTagsRequestTypedDict
from .gettagsresponse import GetTagsResponse, GetTagsResponseTypedDict
from .getworkspaceaccessop import (
    GetWorkspaceAccessRequest,
    GetWorkspaceAccessRequestTypedDict,
)
from .getworkspaceeventsbytargetop import (
    GetWorkspaceEventsByTargetGlobals,
    GetWorkspaceEventsByTargetGlobalsTypedDict,
    GetWorkspaceEventsByTargetRequest,
    GetWorkspaceEventsByTargetRequestTypedDict,
)
from .getworkspacefeatureflagsop import (
    GetWorkspaceFeatureFlagsGlobals,
    GetWorkspaceFeatureFlagsGlobalsTypedDict,
    GetWorkspaceFeatureFlagsRequest,
    GetWorkspaceFeatureFlagsRequestTypedDict,
)
from .getworkspaceop import (
    GetWorkspaceGlobals,
    GetWorkspaceGlobalsTypedDict,
    GetWorkspaceRequest,
    GetWorkspaceRequestTypedDict,
)
from .getworkspacesettingsop import (
    GetWorkspaceSettingsGlobals,
    GetWorkspaceSettingsGlobalsTypedDict,
    GetWorkspaceSettingsRequest,
    GetWorkspaceSettingsRequestTypedDict,
)
from .getworkspacetargetsdeprecatedop import (
    GetWorkspaceTargetsDeprecatedGlobals,
    GetWorkspaceTargetsDeprecatedGlobalsTypedDict,
    GetWorkspaceTargetsDeprecatedRequest,
    GetWorkspaceTargetsDeprecatedRequestTypedDict,
)
from .getworkspacetargetsop import (
    GetWorkspaceTargetsRequest,
    GetWorkspaceTargetsRequestTypedDict,
)
from .getworkspaceteamop import (
    GetWorkspaceTeamGlobals,
    GetWorkspaceTeamGlobalsTypedDict,
    GetWorkspaceTeamRequest,
    GetWorkspaceTeamRequestTypedDict,
)
from .getworkspacetokensop import (
    GetWorkspaceTokensGlobals,
    GetWorkspaceTokensGlobalsTypedDict,
    GetWorkspaceTokensRequest,
    GetWorkspaceTokensRequestTypedDict,
)
from .githubcheckpublishingprsop import (
    GithubCheckPublishingPRsRequest,
    GithubCheckPublishingPRsRequestTypedDict,
)
from .githubcheckpublishingsecretsop import (
    GithubCheckPublishingSecretsRequest,
    GithubCheckPublishingSecretsRequestTypedDict,
)
from .githubconfigurecodesamplesrequest import (
    GithubConfigureCodeSamplesRequest,
    GithubConfigureCodeSamplesRequestTypedDict,
)
from .githubconfigurecodesamplesresponse import (
    GithubConfigureCodeSamplesResponse,
    GithubConfigureCodeSamplesResponseTypedDict,
)
from .githubconfiguremintlifyreporequest import (
    GithubConfigureMintlifyRepoRequest,
    GithubConfigureMintlifyRepoRequestTypedDict,
)
from .githubconfiguretargetrequest import (
    GithubConfigureTargetRequest,
    GithubConfigureTargetRequestTypedDict,
)
from .githubgetactionresponse import (
    GithubGetActionResponse,
    GithubGetActionResponseTypedDict,
)
from .githubmissingpublishingsecretsresponse import (
    GithubMissingPublishingSecretsResponse,
    GithubMissingPublishingSecretsResponseTypedDict,
)
from .githubpublishingprresponse import (
    GithubPublishingPRResponse,
    GithubPublishingPRResponseTypedDict,
)
from .githubsetupstateresponse import (
    Actions,
    ActionsTypedDict,
    GithubSetupStateResponse,
    GithubSetupStateResponseTypedDict,
    Secrets,
    SecretsTypedDict,
)
from .githubstorepublishingsecretsrequest import (
    GithubStorePublishingSecretsRequest,
    GithubStorePublishingSecretsRequestTypedDict,
)
from .githubtriggeractionrequest import (
    GithubTriggerActionRequest,
    GithubTriggerActionRequestTypedDict,
)
from .grantuseraccesstoworkspaceop import (
    GrantUserAccessToWorkspaceGlobals,
    GrantUserAccessToWorkspaceGlobalsTypedDict,
    GrantUserAccessToWorkspaceRequest,
    GrantUserAccessToWorkspaceRequestTypedDict,
)
from .ignoresubscriptionnamespaceop import (
    IgnoreSubscriptionNamespaceRequest,
    IgnoreSubscriptionNamespaceRequestTypedDict,
)
from .interactiontype import InteractionType
from .linkgithubaccessop import (
    LinkGithubAccessRequest,
    LinkGithubAccessRequestTypedDict,
)
from .listremotesourcesop import (
    ListRemoteSourcesRequest,
    ListRemoteSourcesRequestTypedDict,
)
from .manifest import Manifest, ManifestTypedDict
from .namespace import (
    CompositeSpecMetadata,
    CompositeSpecMetadataTypedDict,
    Namespace,
    NamespaceTypedDict,
)
from .oasinfo import License, LicenseTypedDict, OASInfo, OASInfoTypedDict
from .oasoperation import OASOperation, OASOperationTypedDict
from .oassummary import OASSummary, OASSummaryTypedDict
from .organization import Organization, OrganizationTypedDict
from .organizationusage import OrganizationUsage, OrganizationUsageTypedDict
from .organizationusageresponse import (
    OrganizationUsageResponse,
    OrganizationUsageResponseTypedDict,
)
from .posttagsop import PostTagsRequest, PostTagsRequestTypedDict
from .postworkspaceeventsop import (
    PostWorkspaceEventsGlobals,
    PostWorkspaceEventsGlobalsTypedDict,
    PostWorkspaceEventsRequest,
    PostWorkspaceEventsRequestTypedDict,
)
from .preflightrequest import PreflightRequest, PreflightRequestTypedDict
from .preflighttoken import PreflightToken, PreflightTokenTypedDict
from .remotedocument import RemoteDocument, RemoteDocumentTypedDict
from .remotesource import RemoteSource, RemoteSourceTypedDict
from .remotesourcesubscriptionsettings import (
    RemoteSourceSubscriptionSettings,
    RemoteSourceSubscriptionSettingsTypedDict,
)
from .report import Report, ReportTypedDict, Type
from .revision import Revision, RevisionTypedDict
from .revokeuseraccesstoworkspaceop import (
    RevokeUserAccessToWorkspaceGlobals,
    RevokeUserAccessToWorkspaceGlobalsTypedDict,
    RevokeUserAccessToWorkspaceRequest,
    RevokeUserAccessToWorkspaceRequestTypedDict,
)
from .searchworkspaceeventsop import (
    SearchWorkspaceEventsGlobals,
    SearchWorkspaceEventsGlobalsTypedDict,
    SearchWorkspaceEventsRequest,
    SearchWorkspaceEventsRequestTypedDict,
)
from .security import Security, SecurityTypedDict
from .setvisibilityop import (
    SetVisibilityRequest,
    SetVisibilityRequestBody,
    SetVisibilityRequestBodyTypedDict,
    SetVisibilityRequestTypedDict,
)
from .shorturl import ShortURL, ShortURLTypedDict
from .ssometadata import SSOMetadata, SSOMetadataTypedDict
from .suggestitemsrequestbody import (
    SuggestItemsRequestBody,
    SuggestItemsRequestBodyTypedDict,
)
from .suggestop import SuggestRequest, SuggestRequestTypedDict
from .suggestopenapiop import (
    Schema,
    SchemaTypedDict,
    SuggestOpenAPIRequest,
    SuggestOpenAPIRequestBody,
    SuggestOpenAPIRequestBodyTypedDict,
    SuggestOpenAPIRequestTypedDict,
)
from .suggestopenapiregistryop import (
    SuggestOpenAPIRegistryRequest,
    SuggestOpenAPIRegistryRequestTypedDict,
)
from .suggestoptsold import SuggestOptsOld, SuggestOptsOldTypedDict, SuggestionType
from .suggestrequestbody import (
    SuggestRequestBody,
    SuggestRequestBodySuggestionType,
    SuggestRequestBodyTypedDict,
)
from .tag import Tag, TagTypedDict
from .targetsdk import TargetSDK, TargetSDKTypedDict
from .updateworkspacedetailsop import (
    UpdateWorkspaceDetailsGlobals,
    UpdateWorkspaceDetailsGlobalsTypedDict,
    UpdateWorkspaceDetailsRequest,
    UpdateWorkspaceDetailsRequestTypedDict,
)
from .updateworkspacesettingsop import (
    UpdateWorkspaceSettingsGlobals,
    UpdateWorkspaceSettingsGlobalsTypedDict,
    UpdateWorkspaceSettingsRequest,
    UpdateWorkspaceSettingsRequestTypedDict,
)
from .uploadreportop import (
    File,
    FileTypedDict,
    UploadReportRequestBody,
    UploadReportRequestBodyTypedDict,
    UploadReportUploadedReport,
    UploadReportUploadedReportTypedDict,
)
from .user import User, UserTypedDict
from .v2descriptor import V2Descriptor, V2DescriptorTypedDict
from .workflowdocument import (
    AuthModel,
    AuthModelTypedDict,
    WorkflowDocument,
    WorkflowDocumentTypedDict,
)
from .workspace import Workspace, WorkspaceTypedDict
from .workspaceandorganization import (
    WorkspaceAndOrganization,
    WorkspaceAndOrganizationTypedDict,
)
from .workspacefeatureflagresponse import (
    WorkspaceFeatureFlagResponse,
    WorkspaceFeatureFlagResponseTypedDict,
)
from .workspaceinviteresponse import (
    Relationship,
    RelationshipTypedDict,
    WorkspaceInviteResponse,
    WorkspaceInviteResponseTypedDict,
)
from .workspacesettings import WorkspaceSettings, WorkspaceSettingsTypedDict
from .workspaceteamresponse import WorkspaceTeamResponse, WorkspaceTeamResponseTypedDict
from .workspacetoken import WorkspaceToken, WorkspaceTokenTypedDict

__all__ = [
    "APIError",
    "APIKeyDetails",
    "APIKeyDetailsTypedDict",
    "AccessDetails",
    "AccessDetailsTypedDict",
    "AccessToken",
    "AccessTokenTypedDict",
    "AccessTokenUser",
    "AccessTokenUserTypedDict",
    "AccountType",
    "Actions",
    "ActionsTypedDict",
    "ActivateSubscriptionNamespaceRequest",
    "ActivateSubscriptionNamespaceRequestTypedDict",
    "AddTags",
    "AddTagsTypedDict",
    "Annotations",
    "AnnotationsTypedDict",
    "AuthModel",
    "AuthModelTypedDict",
    "CheckGithubAccessRequest",
    "CheckGithubAccessRequestTypedDict",
    "Claims",
    "ClaimsTypedDict",
    "CliEvent",
    "CliEventTypedDict",
    "CodeSampleSchemaInput",
    "CodeSampleSchemaInputTypedDict",
    "CodeSamplesJobStatus",
    "CompositeSpecMetadata",
    "CompositeSpecMetadataTypedDict",
    "CreateRequestBody",
    "CreateRequestBodyTypedDict",
    "CreateWorkspaceTokenGlobals",
    "CreateWorkspaceTokenGlobalsTypedDict",
    "CreateWorkspaceTokenRequest",
    "CreateWorkspaceTokenRequestTypedDict",
    "DeleteWorkspaceTokenGlobals",
    "DeleteWorkspaceTokenGlobalsTypedDict",
    "DeleteWorkspaceTokenRequest",
    "DeleteWorkspaceTokenRequestTypedDict",
    "Diagnostic",
    "DiagnosticTypedDict",
    "Error",
    "ErrorData",
    "FeatureFlag",
    "FeatureFlagTypedDict",
    "File",
    "FileTypedDict",
    "GenerateBumpType",
    "GenerateCodeSamplePreviewAsyncResponseBody",
    "GenerateCodeSamplePreviewAsyncResponseBodyTypedDict",
    "GenerateCodeSamplePreviewResponse",
    "GenerateCodeSamplePreviewResponseTypedDict",
    "GetAccessTokenRequest",
    "GetAccessTokenRequestTypedDict",
    "GetBlobRequest",
    "GetBlobRequestTypedDict",
    "GetChangesReportSignedURLRequest",
    "GetChangesReportSignedURLRequestTypedDict",
    "GetChangesReportSignedURLSignedAccess",
    "GetChangesReportSignedURLSignedAccessTypedDict",
    "GetCodeSamplePreviewAsyncRequest",
    "GetCodeSamplePreviewAsyncRequestTypedDict",
    "GetCodeSamplePreviewAsyncResponse",
    "GetCodeSamplePreviewAsyncResponseBody",
    "GetCodeSamplePreviewAsyncResponseBodyTypedDict",
    "GetCodeSamplePreviewAsyncResponseTypedDict",
    "GetGitHubActionRequest",
    "GetGitHubActionRequestTypedDict",
    "GetGithubSetupStateRequest",
    "GetGithubSetupStateRequestTypedDict",
    "GetLintingReportSignedURLRequest",
    "GetLintingReportSignedURLRequestTypedDict",
    "GetLintingReportSignedURLSignedAccess",
    "GetLintingReportSignedURLSignedAccessTypedDict",
    "GetManifestRequest",
    "GetManifestRequestTypedDict",
    "GetNamespacesResponse",
    "GetNamespacesResponseTypedDict",
    "GetOrganizationRequest",
    "GetOrganizationRequestTypedDict",
    "GetRevisionsRequest",
    "GetRevisionsRequestTypedDict",
    "GetRevisionsResponse",
    "GetRevisionsResponseTypedDict",
    "GetTagsRequest",
    "GetTagsRequestTypedDict",
    "GetTagsResponse",
    "GetTagsResponseTypedDict",
    "GetWorkspaceAccessRequest",
    "GetWorkspaceAccessRequestTypedDict",
    "GetWorkspaceEventsByTargetGlobals",
    "GetWorkspaceEventsByTargetGlobalsTypedDict",
    "GetWorkspaceEventsByTargetRequest",
    "GetWorkspaceEventsByTargetRequestTypedDict",
    "GetWorkspaceFeatureFlagsGlobals",
    "GetWorkspaceFeatureFlagsGlobalsTypedDict",
    "GetWorkspaceFeatureFlagsRequest",
    "GetWorkspaceFeatureFlagsRequestTypedDict",
    "GetWorkspaceGlobals",
    "GetWorkspaceGlobalsTypedDict",
    "GetWorkspaceRequest",
    "GetWorkspaceRequestTypedDict",
    "GetWorkspaceSettingsGlobals",
    "GetWorkspaceSettingsGlobalsTypedDict",
    "GetWorkspaceSettingsRequest",
    "GetWorkspaceSettingsRequestTypedDict",
    "GetWorkspaceTargetsDeprecatedGlobals",
    "GetWorkspaceTargetsDeprecatedGlobalsTypedDict",
    "GetWorkspaceTargetsDeprecatedRequest",
    "GetWorkspaceTargetsDeprecatedRequestTypedDict",
    "GetWorkspaceTargetsRequest",
    "GetWorkspaceTargetsRequestTypedDict",
    "GetWorkspaceTeamGlobals",
    "GetWorkspaceTeamGlobalsTypedDict",
    "GetWorkspaceTeamRequest",
    "GetWorkspaceTeamRequestTypedDict",
    "GetWorkspaceTokensGlobals",
    "GetWorkspaceTokensGlobalsTypedDict",
    "GetWorkspaceTokensRequest",
    "GetWorkspaceTokensRequestTypedDict",
    "GithubCheckPublishingPRsRequest",
    "GithubCheckPublishingPRsRequestTypedDict",
    "GithubCheckPublishingSecretsRequest",
    "GithubCheckPublishingSecretsRequestTypedDict",
    "GithubConfigureCodeSamplesRequest",
    "GithubConfigureCodeSamplesRequestTypedDict",
    "GithubConfigureCodeSamplesResponse",
    "GithubConfigureCodeSamplesResponseTypedDict",
    "GithubConfigureMintlifyRepoRequest",
    "GithubConfigureMintlifyRepoRequestTypedDict",
    "GithubConfigureTargetRequest",
    "GithubConfigureTargetRequestTypedDict",
    "GithubGetActionResponse",
    "GithubGetActionResponseTypedDict",
    "GithubMissingPublishingSecretsResponse",
    "GithubMissingPublishingSecretsResponseTypedDict",
    "GithubPublishingPRResponse",
    "GithubPublishingPRResponseTypedDict",
    "GithubSetupStateResponse",
    "GithubSetupStateResponseTypedDict",
    "GithubStorePublishingSecretsRequest",
    "GithubStorePublishingSecretsRequestTypedDict",
    "GithubTriggerActionRequest",
    "GithubTriggerActionRequestTypedDict",
    "GrantUserAccessToWorkspaceGlobals",
    "GrantUserAccessToWorkspaceGlobalsTypedDict",
    "GrantUserAccessToWorkspaceRequest",
    "GrantUserAccessToWorkspaceRequestTypedDict",
    "IgnoreSubscriptionNamespaceRequest",
    "IgnoreSubscriptionNamespaceRequestTypedDict",
    "InteractionType",
    "Level",
    "License",
    "LicenseTypedDict",
    "LinkGithubAccessRequest",
    "LinkGithubAccessRequestTypedDict",
    "ListRemoteSourcesRequest",
    "ListRemoteSourcesRequestTypedDict",
    "Manifest",
    "ManifestTypedDict",
    "Namespace",
    "NamespaceTypedDict",
    "OASInfo",
    "OASInfoTypedDict",
    "OASOperation",
    "OASOperationTypedDict",
    "OASSummary",
    "OASSummaryTypedDict",
    "OpenapiDiffBumpType",
    "Organization",
    "OrganizationTypedDict",
    "OrganizationUsage",
    "OrganizationUsageResponse",
    "OrganizationUsageResponseTypedDict",
    "OrganizationUsageTypedDict",
    "PostTagsRequest",
    "PostTagsRequestTypedDict",
    "PostWorkspaceEventsGlobals",
    "PostWorkspaceEventsGlobalsTypedDict",
    "PostWorkspaceEventsRequest",
    "PostWorkspaceEventsRequestTypedDict",
    "PreflightRequest",
    "PreflightRequestTypedDict",
    "PreflightToken",
    "PreflightTokenTypedDict",
    "Relationship",
    "RelationshipTypedDict",
    "RemoteDocument",
    "RemoteDocumentTypedDict",
    "RemoteSource",
    "RemoteSourceSubscriptionSettings",
    "RemoteSourceSubscriptionSettingsTypedDict",
    "RemoteSourceTypedDict",
    "Report",
    "ReportTypedDict",
    "Revision",
    "RevisionTypedDict",
    "RevokeUserAccessToWorkspaceGlobals",
    "RevokeUserAccessToWorkspaceGlobalsTypedDict",
    "RevokeUserAccessToWorkspaceRequest",
    "RevokeUserAccessToWorkspaceRequestTypedDict",
    "SSOMetadata",
    "SSOMetadataTypedDict",
    "Schema",
    "SchemaFile",
    "SchemaFileTypedDict",
    "SchemaTypedDict",
    "SearchWorkspaceEventsGlobals",
    "SearchWorkspaceEventsGlobalsTypedDict",
    "SearchWorkspaceEventsRequest",
    "SearchWorkspaceEventsRequestTypedDict",
    "Secrets",
    "SecretsTypedDict",
    "Security",
    "SecurityTypedDict",
    "SetVisibilityRequest",
    "SetVisibilityRequestBody",
    "SetVisibilityRequestBodyTypedDict",
    "SetVisibilityRequestTypedDict",
    "ShortURL",
    "ShortURLTypedDict",
    "SuggestItemsRequestBody",
    "SuggestItemsRequestBodyTypedDict",
    "SuggestOpenAPIRegistryRequest",
    "SuggestOpenAPIRegistryRequestTypedDict",
    "SuggestOpenAPIRequest",
    "SuggestOpenAPIRequestBody",
    "SuggestOpenAPIRequestBodyTypedDict",
    "SuggestOpenAPIRequestTypedDict",
    "SuggestOptsOld",
    "SuggestOptsOldTypedDict",
    "SuggestRequest",
    "SuggestRequestBody",
    "SuggestRequestBodySuggestionType",
    "SuggestRequestBodyTypedDict",
    "SuggestRequestTypedDict",
    "SuggestionType",
    "Tag",
    "TagTypedDict",
    "TargetSDK",
    "TargetSDKTypedDict",
    "Type",
    "UpdateWorkspaceDetailsGlobals",
    "UpdateWorkspaceDetailsGlobalsTypedDict",
    "UpdateWorkspaceDetailsRequest",
    "UpdateWorkspaceDetailsRequestTypedDict",
    "UpdateWorkspaceSettingsGlobals",
    "UpdateWorkspaceSettingsGlobalsTypedDict",
    "UpdateWorkspaceSettingsRequest",
    "UpdateWorkspaceSettingsRequestTypedDict",
    "UploadReportRequestBody",
    "UploadReportRequestBodyTypedDict",
    "UploadReportUploadedReport",
    "UploadReportUploadedReportTypedDict",
    "User",
    "UserTypedDict",
    "V2Descriptor",
    "V2DescriptorTypedDict",
    "WorkflowDocument",
    "WorkflowDocumentTypedDict",
    "Workspace",
    "WorkspaceAndOrganization",
    "WorkspaceAndOrganizationTypedDict",
    "WorkspaceFeatureFlagResponse",
    "WorkspaceFeatureFlagResponseTypedDict",
    "WorkspaceInviteResponse",
    "WorkspaceInviteResponseTypedDict",
    "WorkspaceSettings",
    "WorkspaceSettingsTypedDict",
    "WorkspaceTeamResponse",
    "WorkspaceTeamResponseTypedDict",
    "WorkspaceToken",
    "WorkspaceTokenTypedDict",
    "WorkspaceTypedDict",
    "WorkspacesModel",
    "WorkspacesModelTypedDict",
]
