"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from test_sdk_name_test_package.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Level(str, Enum):
    ALLOWED = "allowed"
    WARNING = "warning"
    BLOCKED = "blocked"


class AccessDetailsTypedDict(TypedDict):
    generation_allowed: bool
    message: str
    level: NotRequired[Level]


class AccessDetails(BaseModel):
    generation_allowed: bool

    message: str

    level: Optional[Level] = None
