"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from test_sdk_name_test_package import utils


class AccountType(str, Enum, metaclass=utils.OpenEnumMeta):
    FREE = "free"
    SCALE_UP = "scale-up"
    BUSINESS = "business"
    ENTERPRISE = "enterprise"
