"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class ActivateSubscriptionNamespaceRequestTypedDict(TypedDict):
    subscription_id: str
    r"""The existing subscription ID"""
    namespace_name: str
    r"""The namespace name"""


class ActivateSubscriptionNamespaceRequest(BaseModel):
    subscription_id: Annotated[
        str,
        pydantic.Field(alias="subscriptionID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The existing subscription ID"""

    namespace_name: Annotated[
        str,
        pydantic.Field(alias="namespaceName"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The namespace name"""
