"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class CheckGithubAccessRequestTypedDict(TypedDict):
    org: str
    repo: str


class CheckGithubAccessRequest(BaseModel):
    org: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    repo: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
