"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspacetoken import WorkspaceToken, WorkspaceTokenTypedDict
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateWorkspaceTokenGlobalsTypedDict(TypedDict):
    workspace_id: NotRequired[str]


class CreateWorkspaceTokenGlobals(BaseModel):
    workspace_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None


class CreateWorkspaceTokenRequestTypedDict(TypedDict):
    workspace_token: WorkspaceTokenTypedDict
    workspace_id_param: NotRequired[str]
    r"""Unique identifier of the workspace."""


class CreateWorkspaceTokenRequest(BaseModel):
    workspace_token: Annotated[
        WorkspaceToken,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    workspace_id_param: Annotated[
        Optional[str],
        pydantic.Field(alias="workspace_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Unique identifier of the workspace."""
