"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .codesamplesjobstatus import CodeSamplesJobStatus
from test_sdk_name_test_package.types import BaseModel
from typing_extensions import TypedDict


class GenerateCodeSamplePreviewAsyncResponseBodyTypedDict(TypedDict):
    r"""Job accepted, returns a job ID to poll for status and result"""

    job_id: str
    r"""The job ID for polling"""
    status: CodeSamplesJobStatus
    r"""The current status of the job. Possible values are `pending` or `running`."""


class GenerateCodeSamplePreviewAsyncResponseBody(BaseModel):
    r"""Job accepted, returns a job ID to poll for status and result"""

    job_id: str
    r"""The job ID for polling"""

    status: CodeSamplesJobStatus
    r"""The current status of the job. Possible values are `pending` or `running`."""
