"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from typing import Union
from typing_extensions import TypeAliasType


GenerateCodeSamplePreviewResponseTypedDict = TypeAliasType(
    "GenerateCodeSamplePreviewResponseTypedDict", Union[httpx.Response, httpx.Response]
)


GenerateCodeSamplePreviewResponse = TypeAliasType(
    "GenerateCodeSamplePreviewResponse", Union[httpx.Response, httpx.Response]
)
