"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetBlobRequestTypedDict(TypedDict):
    organization_slug: str
    workspace_slug: str
    namespace_name: str
    digest: str


class GetBlobRequest(BaseModel):
    organization_slug: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    workspace_slug: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    namespace_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    digest: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
