"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetChangesReportSignedURLRequestTypedDict(TypedDict):
    document_checksum: str
    r"""The checksum of the document to retrieve the signed access url for."""


class GetChangesReportSignedURLRequest(BaseModel):
    document_checksum: Annotated[
        str,
        pydantic.Field(alias="documentChecksum"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The checksum of the document to retrieve the signed access url for."""


class GetChangesReportSignedURLSignedAccessTypedDict(TypedDict):
    r"""OK"""

    url: str


class GetChangesReportSignedURLSignedAccess(BaseModel):
    r"""OK"""

    url: str
