"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetOrganizationRequestTypedDict(TypedDict):
    organization_id: str
    r"""Unique identifier of the organization."""


class GetOrganizationRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the organization."""
