"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workflowdocument import WorkflowDocument, WorkflowDocumentTypedDict
import pydantic
from test_sdk_name_test_package.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GithubConfigureCodeSamplesResponseTypedDict(TypedDict):
    r"""A response to configure GitHub code samples"""

    source: WorkflowDocumentTypedDict
    r"""A document referenced by a workflow"""
    code_sample_overlay_registry_url: str
    r"""The URL of the code sample overlay registry"""
    gh_action_id: NotRequired[str]
    r"""The ID of the GitHub action that was dispatched"""


class GithubConfigureCodeSamplesResponse(BaseModel):
    r"""A response to configure GitHub code samples"""

    source: WorkflowDocument
    r"""A document referenced by a workflow"""

    code_sample_overlay_registry_url: Annotated[
        str, pydantic.Field(alias="codeSampleOverlayRegistryURL")
    ]
    r"""The URL of the code sample overlay registry"""

    gh_action_id: Annotated[Optional[str], pydantic.Field(alias="ghActionID")] = None
    r"""The ID of the GitHub action that was dispatched"""
