"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing_extensions import TypedDict


class GithubConfigureTargetRequestTypedDict(TypedDict):
    r"""A request to configure a GitHub target"""

    org: str
    r"""The GitHub organization name"""
    repo_name: str
    r"""The GitHub repository name"""


class GithubConfigureTargetRequest(BaseModel):
    r"""A request to configure a GitHub target"""

    org: str
    r"""The GitHub organization name"""

    repo_name: str
    r"""The GitHub repository name"""
