"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GithubTriggerActionRequestTypedDict(TypedDict):
    r"""A request to trigger an action on a GitHub target"""

    org: str
    r"""The GitHub organization name"""
    repo_name: str
    r"""The GitHub repository name"""
    gen_lock_id: str
    r"""The generation lock ID"""
    target_name: NotRequired[str]
    r"""The target name for the action"""
    set_version: NotRequired[str]
    r"""A version to override the SDK too in workflow dispatch"""
    force: NotRequired[bool]
    r"""Force an SDK generation"""


class GithubTriggerActionRequest(BaseModel):
    r"""A request to trigger an action on a GitHub target"""

    org: str
    r"""The GitHub organization name"""

    repo_name: str
    r"""The GitHub repository name"""

    gen_lock_id: str
    r"""The generation lock ID"""

    target_name: Optional[str] = None
    r"""The target name for the action"""

    set_version: Optional[str] = None
    r"""A version to override the SDK too in workflow dispatch"""

    force: Optional[bool] = None
    r"""Force an SDK generation"""
