"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing_extensions import TypedDict


class ActionsTypedDict(TypedDict):
    generation_action_configured: bool
    publish_action_configured: bool


class Actions(BaseModel):
    generation_action_configured: bool

    publish_action_configured: bool


class SecretsTypedDict(TypedDict):
    api_key_configured: bool
    publishing_secrets_configured: bool


class Secrets(BaseModel):
    api_key_configured: bool

    publishing_secrets_configured: bool


class GithubSetupStateResponseTypedDict(TypedDict):
    r"""The state of a particular SDK targets github setup"""

    app_installed: bool
    actions: ActionsTypedDict
    secrets: SecretsTypedDict


class GithubSetupStateResponse(BaseModel):
    r"""The state of a particular SDK targets github setup"""

    app_installed: bool

    actions: Actions

    secrets: Secrets
