"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GithubConfigureMintlifyRepoRequestTypedDict(TypedDict):
    r"""A request to configure a GitHub repository for mintlify"""

    org: str
    r"""The GitHub organization name"""
    repo: str
    r"""The GitHub repository name"""
    input: str
    r"""The input OpenAPI document"""
    overlays: List[str]
    r"""The overlays to apply"""
    subdirectory: NotRequired[str]
    r"""The subdirectory (location of mint.json)"""


class GithubConfigureMintlifyRepoRequest(BaseModel):
    r"""A request to configure a GitHub repository for mintlify"""

    org: str
    r"""The GitHub organization name"""

    repo: str
    r"""The GitHub repository name"""

    input: str
    r"""The input OpenAPI document"""

    overlays: List[str]
    r"""The overlays to apply"""

    subdirectory: Optional[str] = None
    r"""The subdirectory (location of mint.json)"""
