"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class GithubCheckPublishingPRsRequestTypedDict(TypedDict):
    generate_gen_lock_id: str
    org: str
    repo: str


class GithubCheckPublishingPRsRequest(BaseModel):
    generate_gen_lock_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    org: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    repo: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
