"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .remotesourcesubscriptionsettings import (
    RemoteSourceSubscriptionSettings,
    RemoteSourceSubscriptionSettingsTypedDict,
)
from datetime import datetime
from test_sdk_name_test_package.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CompositeSpecMetadataTypedDict(TypedDict):
    subscription_id: str
    r"""The subscription ID for the remote source subscription, if applicable. This indicates that the namespace is created by a remote source and thus is composite."""
    subscription_settings: RemoteSourceSubscriptionSettingsTypedDict


class CompositeSpecMetadata(BaseModel):
    subscription_id: str
    r"""The subscription ID for the remote source subscription, if applicable. This indicates that the namespace is created by a remote source and thus is composite."""

    subscription_settings: RemoteSourceSubscriptionSettings


class NamespaceTypedDict(TypedDict):
    r"""A namespace contains many revisions."""

    id: str
    r"""{organization_slug}/{workspace_slug}/{namespace_name}"""
    name: str
    r"""A human-readable name for the namespace."""
    created_at: datetime
    updated_at: datetime
    public: NotRequired[bool]
    r"""Indicates whether the namespace is publicly accessible"""
    composite_spec_metadata: NotRequired[CompositeSpecMetadataTypedDict]


class Namespace(BaseModel):
    r"""A namespace contains many revisions."""

    id: str
    r"""{organization_slug}/{workspace_slug}/{namespace_name}"""

    name: str
    r"""A human-readable name for the namespace."""

    created_at: datetime

    updated_at: datetime

    public: Optional[bool] = None
    r"""Indicates whether the namespace is publicly accessible"""

    composite_spec_metadata: Optional[CompositeSpecMetadata] = None
