"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OASOperationTypedDict(TypedDict):
    method: str
    path: str
    operation_id: str
    description: str
    tags: List[str]
    method_name_override: NotRequired[str]
    group_override: NotRequired[str]


class OASOperation(BaseModel):
    method: str

    path: str

    operation_id: str

    description: str

    tags: List[str]

    method_name_override: Optional[str] = None

    group_override: Optional[str] = None
