"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class OrganizationUsageTypedDict(TypedDict):
    number_of_operations: int
    r"""Number of operations performed"""
    max_operations: int
    r"""Maximum Number of operations per SDK specific in contract"""
    language: str
    r"""The programming language used"""
    used_features: List[str]
    r"""Features that have been used"""
    accessible_features: List[str]
    r"""Features that are accessible"""
    accessible: bool
    r"""Indicates if the features are accessible"""
    workspaces: List[str]
    r"""List of workspace IDs"""
    gen_lock_ids: List[str]
    r"""List of generation lock IDs"""


class OrganizationUsage(BaseModel):
    number_of_operations: int
    r"""Number of operations performed"""

    max_operations: int
    r"""Maximum Number of operations per SDK specific in contract"""

    language: str
    r"""The programming language used"""

    used_features: List[str]
    r"""Features that have been used"""

    accessible_features: List[str]
    r"""Features that are accessible"""

    accessible: bool
    r"""Indicates if the features are accessible"""

    workspaces: List[str]
    r"""List of workspace IDs"""

    gen_lock_ids: List[str]
    r"""List of generation lock IDs"""
