"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addtags import AddTags, AddTagsTypedDict
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostTagsRequestTypedDict(TypedDict):
    namespace_name: str
    add_tags: NotRequired[AddTagsTypedDict]
    r"""A JSON representation of the tags to add"""


class PostTagsRequest(BaseModel):
    namespace_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    add_tags: Annotated[
        Optional[AddTags],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""A JSON representation of the tags to add"""
