"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing_extensions import TypedDict


class PreflightRequestTypedDict(TypedDict):
    namespace_name: str


class PreflightRequest(BaseModel):
    namespace_name: str
