"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from test_sdk_name_test_package.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class RevisionTypedDict(TypedDict):
    id: str
    r"""Format {namespace_id}/{revision_digest}"""
    digest: str
    namespace_name: str
    tags: List[str]
    created_at: datetime
    updated_at: datetime


class Revision(BaseModel):
    id: str
    r"""Format {namespace_id}/{revision_digest}"""

    digest: str

    namespace_name: str

    tags: List[str]

    created_at: datetime

    updated_at: datetime
