"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SetVisibilityRequestBodyTypedDict(TypedDict):
    r"""Namespace visibility"""

    public: bool


class SetVisibilityRequestBody(BaseModel):
    r"""Namespace visibility"""

    public: bool


class SetVisibilityRequestTypedDict(TypedDict):
    namespace_name: str
    request_body: NotRequired[SetVisibilityRequestBodyTypedDict]
    r"""Namespace visibility"""


class SetVisibilityRequest(BaseModel):
    namespace_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        Optional[SetVisibilityRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Namespace visibility"""
