"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .suggestoptsold import SuggestOptsOld, SuggestOptsOldTypedDict
import io
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    HeaderMetadata,
    MultipartFormMetadata,
    RequestMetadata,
)
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class SchemaTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.BufferedReader]
    content_type: NotRequired[str]


class Schema(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None


class SuggestOpenAPIRequestBodyTypedDict(TypedDict):
    r"""The schema file to upload provided as a multipart/form-data file segment."""

    schema_: SchemaTypedDict
    opts: NotRequired[SuggestOptsOldTypedDict]


class SuggestOpenAPIRequestBody(BaseModel):
    r"""The schema file to upload provided as a multipart/form-data file segment."""

    schema_: Annotated[
        Schema,
        pydantic.Field(alias="schema"),
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ]

    opts: Annotated[
        Optional[SuggestOptsOld],
        FieldMetadata(multipart=MultipartFormMetadata(json=True)),
    ] = None


class SuggestOpenAPIRequestTypedDict(TypedDict):
    x_session_id: str
    request_body: SuggestOpenAPIRequestBodyTypedDict
    r"""The schema file to upload provided as a multipart/form-data file segment."""


class SuggestOpenAPIRequest(BaseModel):
    x_session_id: Annotated[
        str,
        pydantic.Field(alias="x-session-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]

    request_body: Annotated[
        SuggestOpenAPIRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]
    r"""The schema file to upload provided as a multipart/form-data file segment."""
