"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SuggestItemsRequestBodyTypedDict(TypedDict):
    prompt: str
    r"""The prompt to use for the suggestion. Think of this as the \"preamble\"."""
    items: List[str]
    r"""The list of \"things\" to get suggestions for. One suggestion will be returned for each item in the list."""


class SuggestItemsRequestBody(BaseModel):
    prompt: str
    r"""The prompt to use for the suggestion. Think of this as the \"preamble\"."""

    items: List[str]
    r"""The list of \"things\" to get suggestions for. One suggestion will be returned for each item in the list."""
