"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .suggestrequestbody import SuggestRequestBody, SuggestRequestBodyTypedDict
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class SuggestRequestTypedDict(TypedDict):
    x_session_id: str
    suggest_request_body: SuggestRequestBodyTypedDict
    r"""The OAS summary and diagnostics to use for the suggestion."""


class SuggestRequest(BaseModel):
    x_session_id: Annotated[
        str,
        pydantic.Field(alias="x-session-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]

    suggest_request_body: Annotated[
        SuggestRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The OAS summary and diagnostics to use for the suggestion."""
