"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing_extensions import TypedDict


class TagTypedDict(TypedDict):
    id: str
    r"""Format {namespace_id}/{tag}"""
    name: str
    r"""Human readable tag name"""
    namespace_name: str
    revision_digest: str


class Tag(BaseModel):
    id: str
    r"""Format {namespace_id}/{tag}"""

    name: str
    r"""Human readable tag name"""

    namespace_name: str

    revision_digest: str
