"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspace import Workspace, WorkspaceTypedDict
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateWorkspaceDetailsGlobalsTypedDict(TypedDict):
    workspace_id: NotRequired[str]


class UpdateWorkspaceDetailsGlobals(BaseModel):
    workspace_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None


class UpdateWorkspaceDetailsRequestTypedDict(TypedDict):
    workspace: WorkspaceTypedDict
    r"""The workspace details to update."""
    workspace_id: NotRequired[str]
    r"""Unique identifier of the workspace."""


class UpdateWorkspaceDetailsRequest(BaseModel):
    workspace: Annotated[
        Workspace, FieldMetadata(request=RequestMetadata(media_type="application/json"))
    ]
    r"""The workspace details to update."""

    workspace_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Unique identifier of the workspace."""
