"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspacesettings import WorkspaceSettings, WorkspaceSettingsTypedDict
import pydantic
from test_sdk_name_test_package.types import BaseModel
from test_sdk_name_test_package.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateWorkspaceSettingsGlobalsTypedDict(TypedDict):
    workspace_id: NotRequired[str]


class UpdateWorkspaceSettingsGlobals(BaseModel):
    workspace_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None


class UpdateWorkspaceSettingsRequestTypedDict(TypedDict):
    workspace_settings: WorkspaceSettingsTypedDict
    r"""The workspace settings to update."""
    workspace_id_param: NotRequired[str]
    r"""Unique identifier of the workspace."""


class UpdateWorkspaceSettingsRequest(BaseModel):
    workspace_settings: Annotated[
        WorkspaceSettings,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The workspace settings to update."""

    workspace_id_param: Annotated[
        Optional[str],
        pydantic.Field(alias="workspace_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Unique identifier of the workspace."""
