"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from test_sdk_name_test_package.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AuthModelTypedDict(TypedDict):
    header: str
    secret: str


class AuthModel(BaseModel):
    header: str

    secret: str


class WorkflowDocumentTypedDict(TypedDict):
    r"""A document referenced by a workflow"""

    location: str
    auth: NotRequired[AuthModelTypedDict]


class WorkflowDocument(BaseModel):
    r"""A document referenced by a workflow"""

    location: str

    auth: Optional[AuthModel] = None
