"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .featureflag import FeatureFlag, FeatureFlagTypedDict
from test_sdk_name_test_package.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class WorkspaceFeatureFlagResponseTypedDict(TypedDict):
    r"""Workspace feature flag response"""

    feature_flags: NotRequired[List[FeatureFlagTypedDict]]


class WorkspaceFeatureFlagResponse(BaseModel):
    r"""Workspace feature flag response"""

    feature_flags: Optional[List[FeatureFlag]] = None
